[run]
version = "mfgp_v1"
output_dir = "../outputs/mfgp"
random_state = 42
verbose = true

[shell]
n_shell = 20 # Shell number to count as outer end of fiducial volume

[training]
min_lf_points = 4
min_hf_points = 4
require_axis_span = true

[model]
alpha_lf_floor = 1.0e-10
alpha_hf = 1.0e-10
kernel_noise = 1e-6
kernel_noise_lim = [1e-10, 1e1]

[prediction]
sigma = 1.0
chunk_size = 20000
progress = true
save_predictions = true