cnp_settings:
  training_mode: minibatch
  training_epochs: 15
  steps_per_epoch: 5000
  context_ratio: 0.05
  context_mode: random
  batch_size_train: 8192
  files_per_batch_train: 16
  ratio_testing_vs_training: 1/10
  plot_after: 5000
simulation_settings:
  n_shells: 100
  theta_headers:
  - detector_R
  - detector_Z
  phi_labels:
  - s_r
  - s_z_from_center
  target_headers:
  - target_shell
  scale_power: 0.3333333333333333
path_settings:
  version: xlzd_shell_v1_minibatch
  path_to_files_train: ../outputs/datasets/training/lf
  path_to_files_predict:
  - ../outputs/datasets/validation/hf
  iteration:
  - 0
  fidelity:
  - 1
  path_out_cnp: ../outputs/cnp
  path_out_mfgp: ../outputs/mfgp